Seafood.WebMvc/Seafood/Controllers/AccountManager/YourAccountController.cs
using Domain.Constant;
using Domain.Models.ResponseModel;
using Seafood.CustomAuthen;
using Seafood.MemCached;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Seafood.Controllers.AccountManager
{
    [SessionAuthen]
    public class YourAccountController : BaseController
    {
        #region YourAccount
        public ActionResult YourAccount(string idItem)
        {
            ViewBag.IdItem = idItem;
            var userData = GetCurrentUser();
            var uri = ApiUri.Get_GetUserById + string.Format($"?userId={userData.UserId}");
            var userDetailt = provider.GetAsync<User>(uri);
            if (userDetailt == null || userDetailt.Result == null || userDetailt.Result.Data == null)
            {
                return View(new User());
            }
            var result = userDetailt.Result.Data;
            return View(result);
        }
        [HttpPost]
        public ActionResult UploadAvartaUser(HttpPostedFileBase imgUpload)
        {
            // kiếm tra dung lượng ảnh
            //var kb_img = (imgUpload.ContentLength / 1024);

            if (imgUpload == null)
            {
                return Json(Success_Request());
            }
            if (imgUpload.FileName.ToLower().Contains(".jpg") || imgUpload.FileName.ToLower().Contains(".png")
                || imgUpload.FileName.ToLower().Contains(".gif") || imgUpload.FileName.ToLower().Contains(".jpeg")
                || imgUpload.FileName.ToLower().Contains(".icon"))
            {
                try
                {
                    var userData = GetCurrentUser();
                    string filePath = string.Empty;
                    string path = string.Format("/FileUpload/seafood/avarta-user/" + userData.UserId.ToString() + "/");
                    filePath = Server.MapPath(path);
                    if (Directory.Exists(filePath))
                    {
                        var dir = new DirectoryInfo(filePath);
                        dir.Delete(true);
                    }
                    Directory.CreateDirectory(filePath);
                    filePath = filePath + Path.GetFileName(imgUpload.FileName);
                    path = path + Path.GetFileName(imgUpload.FileName);
                    imgUpload.SaveAs(filePath);
                    var uri = ApiUri.POST_UserUpdateAvarta + string.Format($"?userId={userData.UserId}&path={path}");
                    var updated = provider.GetAsync<bool>(uri);
                    if (updated == null || updated.Result == null || updated.Result.Data == false || !updated.Result.Success)
                    {
                        return Json(Server_Error());
                    }
                }
                catch
                {
                    return Json(Server_Error());
                }
            }
            else
            {
                return Json(Bad_Request());
            }
            return Json(Success_Request());
        }

        [HttpPost]
        public ActionResult UploadProfileUser(string displayName, string email, int sex, int year, int month, int day)
        {
            var userData = GetCurrentUser();
            var birthday = new DateTime(year, month, day);
            User user = new User()
            {
                Id = userData.UserId,
                DisplayName = displayName,
                Mobile = userData.Mobile,
                Email = email,
                Sex = sex,
                Birthday = birthday
            };
            var uri = ApiUri.POST_UserUploadProfile;
            var updated = provider.PostAsync<User>(uri, user);
            if (updated == null || updated.Result == null || updated.Result.Data == null || !updated.Result.Success)
            {
                return Json(Server_Error());
            }
            Authenticator.SetAuth(updated.Result.Data, HttpContext);
            return Json(Success_Request());
        }
        #endregion YourAccount
    }
}

Seafood.WebMvc/Seafood/Controllers/YourAccountController.cs
using Domain.Constant;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Seafood.Controllers
{
    public class YourAccountController : BaseController
    {
        #region YourAccount
        public ActionResult YourAccount(string idItem)
        {
            ViewBag.IdItem = idItem;
            return View();
        }
        [HttpPost]
        public ActionResult UploadAvartaUser(HttpPostedFileBase imgUpload)
        {
            // kiếm tra dung lượng ảnh
            //var kb_img = (imgUpload.ContentLength / 1024);

            if (imgUpload == null)
            {
                return Json(Success_Request());
            }
            if (imgUpload.FileName.ToLower().Contains(".jpg") || imgUpload.FileName.ToLower().Contains(".png")
                || imgUpload.FileName.ToLower().Contains(".gif") || imgUpload.FileName.ToLower().Contains(".jpeg")
                || imgUpload.FileName.ToLower().Contains(".icon"))
            {
                try
                {
                    var updated = provider.PostAsync<HttpPostedFileBase>(ApiUri.POST_AccountUpdateAvarta, imgUpload);
                    if (updated == null || updated.Result == null || updated.Result.Data == null || !updated.Result.Success)
                    {
                        return Json(Server_Error());
                    }
                }
                catch
                {
                    return Json(Server_Error());
                }
            }
            else
            {
                return Json(Bad_Request());
            }
            return Json(Success_Request());
        }

        [HttpPost]
        public ActionResult UploadProfileUser(string displayName, string email, string sex, int year, int month, int day)
        {

            var birthday = new DateTime(year, month, day);
            return Json(Success_Request());
        }
        #endregion YourAccount
    }
}

Seafood.WebMvc/Seafood/Views/YourAccount/YourAccount.cshtml
@using Domain.Constant
@using Service.Helpers;
@{
    Layout = "~/Views/Shared/_LayoutAccountManager.cshtml";
    string domainName = HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority);
    var masterDataHelper = new MasterDataHelper();
    var listRegion = masterDataHelper.GetListRegion();
}
@model Domain.Models.ResponseModel.User
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/assets/css/demo/account-manager/your-account.css" rel="stylesheet" />
    <style>
        /*ghi đè class*/
        .container-layout-account-manager {
            padding: 0 20px 0 20px;
        }
                .box-update-account .form-control-update-account .input-update:focus {
                    border: 1px solid rgb(7, 171, 226);
                }

        .container-update-account .col-1, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7, .col-8, .col-9, .col-10, .col-11, .col-12, .col, .col-auto,
        .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10,
        .col-sm-11, .col-sm-12, .col-sm, .col-sm-auto, .col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6,
        .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12, .col-md, .col-md-auto, .col-lg-1,
        .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9,
        .col-lg-10, .col-lg-11, .col-lg-12, .col-lg, .col-lg-auto, .col-xl-1, .col-xl-2, .col-xl-3, .col-xl-4, .col-xl-5,
        .col-xl-6, .col-xl-7, .col-xl-8, .col-xl-9, .col-xl-10, .col-xl-11, .col-xl-12, .col-xl, .col-xl-auto {
            padding-right: 0;
            padding-left: 0;
        }
    </style>
</head>

<body>
    <div class="container-update-account">
        <div class="heading">
            <h3>Tài khoản của bạn</h3>
        </div>
        <form enctype="multipart/form-data">
            <div class="col-md-3 col-sm-12">
                <div class="box-avatar-user">
                    <div class="avatar">
                        @{
                            if (string.IsNullOrEmpty(Model.Avarta))
                            {
                                <img id="img_preview" src="@string.Format(domainName + Constant.Link_Empty_Avarta_User)" alt="avatar">
                            }
                            else
                            {
                                <img id="img_preview" src="@string.Format(domainName + Model.Avarta)" alt="avatar">
                            }
                        }

                    </div>
                    <label for="file_input">Chọn ảnh</label>
                    <input accept="image/*" name="imgUpload" type="file" id="file_input" />
                </div>
            </div>
            <div class="col-md-9 col-sm-12 menu">
                <div class="box-update-account">
                    <div class="form-control-update-account">
                        <label class="label-update">Họ và tên:</label>
                        <input id="display_name" required class="input-update" placeholder="Nhập họ và tên" maxlength="60" value="@Model.DisplayName">
                    </div>
                    <div class="form-control-update-account">
                        <label class="label-update">Email:</label>
                        @{
                            if (string.IsNullOrEmpty(Model.Email))
                            {
                                <input id="email" class="input-update" placeholder="Nhập email" maxlength="100" value="">
                            }
                            else
                            {
                                <input id="email" class="input-update" placeholder="Nhập email" maxlength="100" value="@Model.Email">
                            }
                        }
                    </div>
                    <div class="form-control-update-account">
                        <label class="label-update">Số điện thoại:</label>
                        <input id="mobile" disabled class="input-update" maxlength="10" value="@Model.Mobile.Trim()">
                    </div>
                    <div class="form-control-update-account">
                        <label class="label-update">Ngày sinh:</label>
                        <div class="box-check-birthday-option">
                            <select id="birthday" class="form-select" aria-label="Default select example">
                                @{
                                    for (int day = 1; day <= 31; day++)
                                    {
                                        if (@Model.Birthday.Day == day)
                                        {
                                            <option selected value="@day">@day</option>
                                            continue;
                                        }
                                        <option value="@day">@day</option>
                                    }
                                }
                            </select>
                            <select id="birthmonth" class="form-select" aria-label="Default select example">
                                @{
                                    for (int month = 1; month <= 12; month++)
                                    {
                                        if (@Model.Birthday.Month == month)
                                        {
                                            <option selected value="@month">Tháng @month</option>
                                            continue;
                                        }
                                        <option value="@month">Tháng @month</option>
                                    }
                                }
                            </select>
                            <select id="birthyear" class="form-select" aria-label="Default select example">
                                @for (int year = DateTime.Now.Year; year >= 1900; year--)
                                {
                                    if (@Model.Birthday.Year == year)
                                    {
                                        <option selected value="@year">@year</option>
                                        continue;
                                    }
                                    <option value="@year">@year</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="form-control-update-account">
                        <label class="label-update">Giới tính:</label>
                        <div class="box-check-radio-option">
                            @{
                                if (Model.Sex == 1)
                                {
                                    <input type="radio" id="option_sex_nam" name="radio_option_sex" value="1" checked="checked" />
                                    <label for="contactChoice1">Nam</label>
                                    <input type="radio" id="option_sex_nu" name="radio_option_sex" value="0" />
                                    <label for="contactChoice2">Nữ</label>
                                    <input type="radio" id="option_sex_khac" name="radio_option_sex" value="-1" />
                                    <label for="contactChoice2">Khác</label>
                                }
                                else if (Model.Sex == 0)
                                {
                                    <input type="radio" id="option_sex_nam" name="radio_option_sex" value="1"/>
                                    <label for="contactChoice1">Nam</label>
                                    <input type="radio" id="option_sex_nu" name="radio_option_sex" value="0" checked="checked"/>
                                    <label for="contactChoice2">Nữ</label>
                                    <input type="radio" id="option_sex_khac" name="radio_option_sex" value="-1" />
                                    <label for="contactChoice2">Khác</label>
                                }
                                else
                                {
                                    <input type="radio" id="option_sex_nam" name="radio_option_sex" value="1"/>
                                    <label for="contactChoice1">Nam</label>
                                    <input type="radio" id="option_sex_nu" name="radio_option_sex" value="0" />
                                    <label for="contactChoice2">Nữ</label>
                                    <input type="radio" id="option_sex_khac" name="radio_option_sex" value="-1" checked="checked"/>
                                    <label for="contactChoice2">Khác</label>
                                }
                            }
                        </div>
                    </div>
                    <div class="form-control-update-account">
                        <label class="label-update"></label>
                        <div class="box-click-continue">
                            <button onclick="updateInfoAccount()" class="btn-core-accept" type="button">Cập nhật</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <script>
        //Setup
        const fileInput = document.getElementById('file_input');
        const imgPreview = document.getElementById('img_preview');

        fileInput.addEventListener('change', (e) => {
            if (e.target.files.length) {
                const src = URL.createObjectURL(e.target.files[0]);
                imgPreview.src = src;
            }
        });
        $(document).ready(function () {
        });
        //Setup
        function updateInfoAccount()
        {
            var displayName = document.getElementById("display_name").value;
            var email = document.getElementById("email").value;
            var sex = $("input[type='radio'][name='radio_option_sex']:checked").val();
            var year = document.getElementById("birthyear").value;
            var month = document.getElementById("birthmonth").value;
            var day = document.getElementById("birthday").value;

            if (isNullOrEmpty(displayName))
            {
                showToasinette_Error_Top_Right('Tên hiển thị không được bỏ trống');
                return;
            }
            var formData = new FormData($('form')[0]);
            ShowOverlay(true);
            $.ajax({
                cache: false,
                contentType: false,
                processData: false,
                data: formData,
                url: "@Url.Action("UploadAvartaUser", "YourAccount")",
                type: 'Post',
                beforeSend: function ()
                {
                },
                success: function (data)
                {
                    if (data.Success) {
                        $.ajax({
                            type: "POST",
                            traditional: true,
                            data:
                            {
                                "displayName": displayName,
                                "email": email,
                                "sex": sex,
                                "year": year,
                                "month": month,
                                "day": day,
                            },
                            url: "@Url.Action("UploadProfileUser", "YourAccount")",
                            success: function (data)
                            {
                                hideOverlay();
                                showToasinette_AwesomeAlert();
                            },
                        })
                    }
                    else
                    {
                        hideOverlay();
                        showToasinette_Error_Top_Right();
                    }
                },
                error: function ()
                {
                    hideOverlay();
                    showToasinette_Error_Top_Right();
                },
            });
        }
    </script>
</body>
</html>